language: node_js
node_js:
  - '10'
before_script:
  - npm install -g gulp
  - npm install gulp
  - npm install browser-sync --save-dev
  - npm install -g gulp-concat
  - npm install -g gulp-sourcemaps
script: gulp
